String-handling tweaks, safety & shellchecking
 - `gecp` should break less easily outside a job
 - added quotes to, like, a billion variable expansions
 - preferred `[[` to `[`
 - preferred `$(())` to deprecated `$[]`
 - several cases of replacing `$*` with `"$@"` for command-line
 continuation
 - added line breaks to some long command-lines to make them easier to
 read and edit
 - made error message for `gerun-` slightly clearer and added module
 list dump to make support easier for us

diff --git a/gecp b/gecp
--- a/gecp
+++ b/gecp
@@ -9,14 +9,27 @@
 
 # For licensing terms, see LICENSE.txt
 
-sort -u $TMPDIR/machines > $TMPDIR/uniqmachines
+if [[ ! -d "$TMPDIR" ]]; then
+  echo "Error: no TMPDIR set: gecp cannot find \$TMPDIR/machines"
+  exit 2
+fi
 
-cat $TMPDIR/uniqmachines
+if [[ ! -r "$TMPDIR/machines" ]]; then
+  echo "Error: no machinefile: gecp cannot find $TMPDIR/machines"
+  exit 3
+fi
 
-for a in `cat $TMPDIR/uniqmachines`
-do
-  qrsh -inherit $a "cd `pwd`; /bin/cp $*" &
-  pids="$pids $!"
+sort -u "$TMPDIR/machines" > "$TMPDIR/uniqmachines"
+
+echo "Using nodes:" >&2
+cat "$TMPDIR/uniqmachines" >&2
+
+declare -a pids
+for node in $(cat "$TMPDIR/uniqmachines"); do
+  # TODO Think of a way to fix this --v
+  # WARN: This will break if any of the command line arguments contain spaces
+  qrsh -inherit "$node" "cd \"$(pwd)\"; /bin/cp $*" &
+  pids+=("$!")
 done
 
-wait $pids
+wait "${pids[@]}"
diff --git a/gerun- b/gerun-
--- a/gerun-
+++ b/gerun-
@@ -6,4 +6,9 @@
 # For licensing terms, see LICENSE.txt
 
 # Fail and print useful error if no MPI loaded.
-echo You don\'t appear to have an MPI implementation loaded.  Exiting.
+echo "Error: You don't appear to have an MPI implementation loaded.  Exiting." >&2
+
+if declare -f module >/dev/null; then
+  echo ""
+  module list -t
+fi
